# constants/schema.py

from typing import Dict, List, Tuple

# 각 테이블의 스키마: (컬럼명, 데이터 타입, 제약 조건)
# 제약 조건은 빈 문자열이면 없음, "NOT NULL", "DEFAULT 1" 등
SCHEMAS = {
    "school_info": {
        "table_name": "schools",  # 실제 테이블명
        "columns": [
            ("school_code", "TEXT", "PRIMARY KEY"),
            ("school_name", "TEXT", "NOT NULL"),
            ("region_code", "TEXT", "NOT NULL"),
            ("atpt_ofcdc_org_nm", "TEXT", ""),
            ("atpt_ofcdc_org_code", "TEXT", ""),
            ("ju_org_nm", "TEXT", ""),
            ("ju_org_code", "TEXT", ""),
            ("adrcd_nm", "TEXT", ""),
            ("adrcd_cd", "TEXT", ""),
            ("lctn_sc_code", "TEXT", ""),
            ("schul_nm", "TEXT", ""),
            ("schul_knd_sc_code", "TEXT", ""),
            ("fond_sc_code", "TEXT", ""),
            ("hs_knd_sc_nm", "TEXT", ""),
            ("bnhh_yn", "TEXT", ""),
            ("schul_fond_typ_code", "TEXT", ""),
            ("dght_sc_code", "TEXT", ""),
            ("foas_memrd", "TEXT", ""),
            ("fond_ymd", "TEXT", ""),
            ("adres_brkdn", "TEXT", ""),
            ("dtlad_brkdn", "TEXT", ""),
            ("zip_code", "TEXT", ""),
            ("schul_rdnzc", "TEXT", ""),
            ("schul_rdnma", "TEXT", ""),
            ("schul_rdnda", "TEXT", ""),
            ("lttud", "REAL", ""),
            ("lgtud", "REAL", ""),
            ("user_telno", "TEXT", ""),
            ("user_telno_sw", "TEXT", ""),
            ("user_telno_ga", "TEXT", ""),
            ("perc_faxno", "TEXT", ""),
            ("hmpg_adres", "TEXT", ""),
            ("coedu_sc_code", "TEXT", ""),
            ("absch_yn", "TEXT", ""),
            ("absch_ymd", "TEXT", ""),
            ("close_yn", "TEXT", ""),
            ("schul_crse_sc_value", "TEXT", ""),
            ("schul_crse_sc_value_nm", "TEXT", ""),
            ("collected_at", "TEXT", "NOT NULL"),
            ("updated_at", "TEXT", ""),
            ("is_active", "INTEGER", "DEFAULT 1"),
            ("in_neis", "INTEGER", "DEFAULT 0"),
        ],
        "indexes": [
            ("idx_schools_region", "atpt_ofcdc_org_code"),
            ("idx_schools_type", "schul_knd_sc_code"),
            ("idx_schools_in_neis", "in_neis"),
        ],
    },
    "neis_info": {
        "table_name": "schools",
        "columns": [
            ("sc_code", "TEXT", "PRIMARY KEY"),
            ("school_id", "INTEGER", ""),
            ("sc_name", "TEXT", ""),
            ("eng_name", "TEXT", ""),
            ("sc_kind", "TEXT", ""),
            ("atpt_code", "TEXT", ""),
            ("address", "TEXT", ""),
            ("cleaned_address", "TEXT", ""),
            ("address_hash", "TEXT", ""),
            ("tel", "TEXT", ""),
            ("homepage", "TEXT", ""),
            ("status", "TEXT", "DEFAULT '운영'"),
            ("last_seen", "INTEGER", ""),
            ("load_dt", "TEXT", ""),
            ("latitude", "REAL", ""),
            ("longitude", "REAL", ""),
            ("geocode_attempts", "INTEGER", "DEFAULT 0"),
            ("last_error", "TEXT", ""),
            ("city_id", "INTEGER", ""),
            ("district_id", "INTEGER", ""),
            ("street_id", "INTEGER", ""),
            ("number_type", "TEXT", ""),
            ("number_value", "INTEGER", ""),
            ("number_start", "INTEGER", ""),
            ("number_end", "INTEGER", ""),
            ("number_bit", "INTEGER", ""),
            ("kakao_address", "TEXT", ""),
            ("jibun_address", "TEXT", ""),
            ("atpt_ofcdc_sc_nm", "TEXT", ""),
            ("lctn_sc_nm", "TEXT", ""),
            ("ju_org_nm", "TEXT", ""),
            ("fond_sc_nm", "TEXT", ""),
            ("org_rdnzc", "TEXT", ""),
            ("org_rdnda", "TEXT", ""),
            ("org_faxno", "TEXT", ""),
            ("coedu_sc_nm", "TEXT", ""),
            ("hs_sc_nm", "TEXT", ""),
            ("indst_specl_ccccl_exst_yn", "TEXT", ""),
            ("hs_gnrl_busns_sc_nm", "TEXT", ""),
            ("spcly_purps_hs_ord_nm", "TEXT", ""),
            ("ene_bfe_sehf_sc_nm", "TEXT", ""),
            ("dght_sc_nm", "TEXT", ""),
            ("fond_ymd", "TEXT", ""),
            ("foas_memrd", "TEXT", ""),
            ("load_dtm", "TEXT", ""),
        ],
        "indexes": [
            ("idx_address_hash", "address_hash"),
            ("idx_city", "city_id"),
            ("idx_district", "district_id"),
            ("idx_street", "street_id"),
            ("idx_schools_missing", "latitude", "WHERE latitude IS NULL"),
            ("idx_schools_region", "atpt_code"),
        ],
    },
    # 필요에 따라 meal, timetable 등 추가
}
