name: Auto Pull on Server
on:
  push:
    branches: [ main ]

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and pull
        uses: appleboy/ssh-action@master
        with:
          host: 168.107.60.11  # 직접 IP 입력
          username: ubuntu     # 직접 아이디 입력
          key: ${{ secrets.ORACLE_SSH_KEY }}
          port: 22
          host_key_check: false
          script: |
            cd /home/ubuntu/Hi-Dunkey
            git pull origin main
            echo "✅ Pull 완료: $(date)"